# forms.py

from wtforms import Form, StringField, SelectField, validators

class EquipmentSearchForm(Form):
    search = StringField('')

class iEquipmentForm(Form):
    names = [('Outside micrometer', 'Outside micrometer'),('Inside micrometer', 'Inside micrometer'),('Vernier caliper', 'Vernier caliper'),('Vernier Depth gauge','Vernier Depth gauge'),('Depth micrometer','Depth micrometer')]
    typee = SelectField('Type', choices=names)
    rangee =StringField('Range')
    make=StringField('Make')
    source=StringField('Source')
    procdate=StringField('Procured Date')
    accept=StringField('Acceptance Standard')
    lc = StringField('Least Count')
    freq=StringField('Freaquency')
    stock=StringField('Stock Status')
    center=StringField('Center')
    locid=StringField('Location ID')
    status = StringField('Status')
    #lastissue=StringField('Last Issue Date')
    #creationdate=StringField('Creation Date')
    #lastedit=StringField('Last Edit')
    ticketno=StringField('Ticket Number')
    empname=StringField('Employee Name')

class gEquipmentForm(Form):
    names = [('Outside micrometer', 'Outside micrometer'),('Inside micrometer', 'Inside micrometer'),('Vernier caliper', 'Vernier caliper'),('Vernier Depth gauge','Vernier Depth gauge'),('Depth micrometer','Depth micrometer')]
    typee = SelectField('Type', choices=names)    
    rangee =StringField('Gauge Size')
    make=StringField('Make')
    source=StringField('Source')
    procdate=StringField('Procured Date')
    accept=StringField('Acceptance Standard')
    lc = StringField('Accuracy')
    freq=StringField('Freaquency')
    stock=StringField('Stock Status')
    center=StringField('Center')
    locid=StringField('Location ID')
    status = StringField('Status')
    #lastissue=StringField('Last Issue Date')
    #creationdate=StringField('Creation Date')
    #lastedit=StringField('Last Edit')
    ticketno=StringField('Ticket Number')
    empname=StringField('Employee Name')
    ngmin=StringField('New Go Min')
    ngmax=StringField('New Go Max')
    gumin=StringField('Go Used Min')
    gumax=StringField('Go Used Max')
    nogmin=StringField('No Go Min')
    nogmax=StringField('No Go Max')
    sizemin=StringField('Size Min')
    sizemax=StringField('Size Max')

class uiEquipmentForm(Form):
    itemcode = StringField('Instrument ID')
    masterref=StringField('Master Reference')
    calibby=StringField('Frequency')
    remarks=StringField('Remarks')
    sd1=StringField('Set Dimension 1')
    sd2=StringField('Set Dimension 2')
    sd3=StringField('Set Dimension 3')
    sd4=StringField('Set Dimension 4')
    sd5=StringField('Set Dimension 5')
    od1=StringField('Original Dimension 1')
    od2=StringField('Original Dimension 2')
    od3=StringField('Original Dimension 3')
    od4=StringField('Original Dimension 4')
    od5=StringField('Original Dimension 5')

class ugEquipmentForm(Form):
    itemcode = StringField('Instrument ID')
    masterref=StringField('Master Reference')
    calibby=StringField('Frequency')
    remarks=StringField('Remarks')
    gmajd1=StringField('Go maj. dia1.')
    ngmajd1=StringField('No go maj. dia1.')
    geffd1=StringField('Go eff. dia1.')
    ngeffd1=StringField('No go eff. dia1.')
    gpitd1=StringField('Go pitch. dia1.')
    ngpitd1=StringField('No go pitch. dia1.')
    gmajd2=StringField('Go maj. dia2.')
    ngmajd2=StringField('No go maj. dia2.')
    geffd2=StringField('Go eff. dia2.')
    ngeffd2=StringField('No go eff. dia2.')
    gpitd2=StringField('Go pitch. dia2.')
    ngpitd2=StringField('No go pitch. dia2.')
