from app import db

class Equipment(db.Model):
    """"""
    __tablename__ = "equipment"

    id = db.Column(db.Integer, primary_key=True)
    itemcode = db.Column(db.String)
    typee=db.Column(db.String)
    rangee = db.Column(db.String)
    make=db.Column(db.String)
    procdate=db.Column(db.String)
    source=db.Column(db.String)
    accept=db.Column(db.String)
    lc = db.Column(db.String)
    freq=db.Column(db.String)
    stock=db.Column(db.String)
    center=db.Column(db.String)
    locid=db.Column(db.String)
    status = db.Column(db.String)
    #lastissue=db.Column(db.String)
    #creationdate=db.Column(db.String)
    #lastedit=db.Column(db.String)
    ticketno=db.Column(db.String)
    empname=db.Column(db.String)
    ngmin=db.Column(db.String)
    ngmax=db.Column(db.String)
    gumin=db.Column(db.String)
    gumax=db.Column(db.String)
    nogmin=db.Column(db.String)
    nogmax=db.Column(db.String)
    sizemin=db.Column(db.String)
    sizemax=db.Column(db.String)

class History(db.Model):
    """"""
    __tablename__ = "history"

    id = db.Column(db.Integer, primary_key=True)
    itemcode = db.Column(db.String)
    masterref=db.Column(db.String)
    chkdate=db.Column(db.String)
    calibby=db.Column(db.String)
    remarks=db.Column(db.String)
    nextcalib=db.Column(db.String)
    sd1=db.Column(db.String)
    sd2=db.Column(db.String)
    sd3=db.Column(db.String)
    sd4=db.Column(db.String)
    sd5=db.Column(db.String)
    od1=db.Column(db.String)
    od2=db.Column(db.String)
    od3=db.Column(db.String)
    od4=db.Column(db.String)
    od5=db.Column(db.String)
    gmajd1=db.Column(db.String)
    ngmajd1=db.Column(db.String)
    geffd1=db.Column(db.String)
    ngeffd1=db.Column(db.String)
    gpitd1=db.Column(db.String)
    ngpitd1=db.Column(db.String)
    gpitd2=db.Column(db.String)
    ngpitd2=db.Column(db.String)
    gmajd2=db.Column(db.String)
    ngmajd2=db.Column(db.String)
    geffd2=db.Column(db.String)
    ngeffd2=db.Column(db.String)
